#! /bin/sh

[ -d ${HOME}/.falkon ] || {
  mkdir -p ${HOME}/.falkon
  cp -f ${APPDIR}/share/qt5/resources/* ${HOME}/.falkon
}

[ -d ${HOME}/.QtWebEngineProcess ] || {
  mkdir -p ${HOME}/.QtWebEngineProcess
  cp -f ${APPDIR}/share/qt5/resources/* ${HOME}/.QtWebEngineProcess
}

export LD_LIBRARY_PATH=$APPDIR/usr/lib:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/lib/x86_64-linux-gnu:$APPDIR/lib:$LD_LIBRARY_PATH
export PATH=$APPDIR/bin:$APPDIR/sbin:$APPDIR/usr/bin:$APPDIR/usr/sbin:$PATH
exec ${APPDIR}/usr/bin/falkon "${@}"
